# docker compose version
version: '3.8'
# all the containers have to declare inside services
services:
  postgres:
    container_name: salary-hero-db
    image: postgres:13
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DATABASE_CONTAINER_PORT}:${POSTGRES_PORT}
    networks:
      - salary-hero-net
    restart: unless-stopped

  salary-hero:
    container_name: salary-hero
    image: salary-hero
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - salary-hero-net
    restart: always

  migration:
    image: salary-hero
    env_file:
      - .env
    command: npm run migration:up
    depends_on:
      - postgres
    networks:
      - salary-hero-net

networks:
  salary-hero-net:
    driver: bridge
    external: true

# save (persist) data
volumes:
  db: {}